# Generated by Django 4.2.1 on 2023-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_district_alter_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
